export function decode(html){const out=[];for(const m of html.matchAll(/self\.__next_f\.push\((\[.*?\])\)<\/script>/gs)){try{const t=JSON.parse(m[1])[1];if(typeof t==='string'){const p=t.indexOf(':');out.push(JSON.parse(t.slice(p+1)))}}catch{}}return out}
function find(all,key){for(const v of all){if(v&&typeof v==='object'){if(Object.hasOwn(v,key))return v[key];const r=find(Object.values(v),key);if(r!==undefined)return r}}}
const clean=s=>String(s||'').replace(/<[^>]*>/g,'').trim();
export function attractionTerms(value=''){if(typeof value!=='string'||value.length>200)throw Error('景點需求請控制在 200 字以內。');const terms=[...new Set(value.split(/[、，,；;\n]+/).map(x=>x.trim()).filter(Boolean))];if(terms.length>8)throw Error('一次最多填寫 8 個景點。');return terms}
export function attractionMatch(info,terms){const sights=(info?.Itinerary_Info?.Itinerary_Info_list||[]).flatMap(day=>(day.SightInfoList||[]).map(s=>clean(s.Sight_Name))).filter(Boolean);const normalize=s=>s.normalize('NFKC').replace(/\s+/g,'').toLowerCase();return terms.map(term=>({term,evidence:sights.filter(s=>normalize(s).includes(normalize(term)))}))}
async function page(url){const r=await fetch(url,{signal:AbortSignal.timeout(18000),headers:{'Accept':'text/html'}});if(!r.ok)throw Error('官網暫時無法讀取，請稍後重試或開啟官網查詢。');return decode(await r.text())}
export function validate(q){if(!q||typeof q.destination!=='string'||!q.destination.trim()||q.destination.length>60)throw Error('請輸入國家或地區。');for(const k of ['start','end'])if(!/^\d{4}-\d{2}-\d{2}$/.test(q[k])||!Number.isFinite(Date.parse(q[k]))||new Date(q[k]).toISOString().slice(0,10)!==q[k])throw Error('請填寫有效日期。');if(q.end<q.start)throw Error('結束日期不可早於開始日期。');if((new Date(q.end)-new Date(q.start))/86400000>366)throw Error('請將出發日期範圍縮小至一年內。');for(const k of ['adults','children','infants','seniors'])if(!Number.isInteger(q[k])||q[k]<0||q[k]>99)throw Error('人數需為 0–99 的整數。');if(q.adults+q.seniors<1)throw Error('請至少填寫一位成人或長者。');attractionTerms(q.attractions);return q}
export async function search(input){const q=validate(input);const requestedAttractions=attractionTerms(q.attractions);const url=new URL('https://tour.colatour.com.tw/search');url.searchParams.set('KeyWord',q.destination.trim());const raw=await page(url);const groups=find(raw,'Tour_Data');if(!Array.isArray(groups))throw Error('官網資料格式已變動，請改用官網查詢。');const candidates=[];function walk(v){if(!v||typeof v!=='object')return;if(v.Pattern_No&&v.Tour_Title){if(!candidates.some(t=>t.Pattern_No===v.Pattern_No))candidates.push(v);return}Object.values(v).forEach(walk)}walk(groups);
const slots=q.adults+q.children+q.seniors;const dates=new Set();for(let d=new Date(q.start);d<=new Date(q.end)&&dates.size<367;d.setUTCDate(d.getUTCDate()+1))dates.add(d.toISOString().slice(5,10).replace('-','/'));
const shortlist=candidates.filter(t=>!t.Departure_Date?.length||t.Departure_Date.some(d=>dates.has(d))).slice(0,18);const results=[];let failed=0,checked=0;
for(let i=0;i<shortlist.length&&(requestedAttractions.length>0||results.length<3);i+=3){await Promise.all(shortlist.slice(i,i+3).map(async t=>{try{const data=await page('https://tour.colatour.com.tw/itinerary?PatternNo='+encodeURIComponent(t.Pattern_No));const info=find(data,'itineraryData');const by=find(data,'itineraryByTourCode');checked++;const departures=by?.Tour_Goday?.TourMonthList?.flatMap(m=>m.Tour_Goday_list||[])||[];const eligible=departures.filter(d=>{const date=d.Tour_Date?.replaceAll('/','-');const m=/^可售\s*(\d+)$/.exec(d.Available_Pax||'');return date>=q.start&&date<=q.end&&d.SignUp_Mark===true&&!d.App_Product_Mark&&m&&Number(m[1])>=slots}).sort((a,b)=>a.Tour_Date.localeCompare(b.Tour_Date));if(!eligible.length)return;const d=eligible[0];const detail=by?.Tour_Goday?.Departure_Date_List?.flatMap(x=>x.Departure_Date_Detail||[]).find(x=>x.Tour_Code===d.Tour_Code);const link=new URL('https://tour.colatour.com.tw/itinerary');link.searchParams.set('PatternNo',t.Pattern_No);const words=clean(info?.Selling_Point||t.Tour_Description);const attractions=attractionMatch(info,requestedAttractions);results.push({attractions,attractionScore:attractions.filter(x=>x.evidence.length).length,id:t.Pattern_No,title:clean(t.Tour_Title),date:d.Tour_Date,price:d.Retail_Price,seats:d.Available_Pax,days:info?.Tour_Days||'',description:words.slice(0,180),image:t.Tour_Image,url:link.href,code:d.Tour_Code,departure:detail?.FlightData?.[0]?.FlightData_GoList?.[0]?.City_Name_D||'待確認',reason:'出發日期符合，官網可售席位足供 '+slots+' 位需占位旅客。',notes:[q.children?'兒童年齡、占床與售價待確認。':'',q.infants?'嬰兒名額、年齡與費用待確認，未納入一般席位。':'',q.seniors?'長者體力、步行與上下車安排待確認。':'','房型與最終團位需再次確認。'].filter(Boolean)});}catch{failed++}}))}
results.sort((a,b)=>b.attractionScore-a.attractionScore||a.date.localeCompare(b.date)||a.title.localeCompare(b.title));return {results:results.slice(0,3),checked,failed,total:candidates.length,source:url.href,queriedAt:new Date().toISOString(),notice:requestedAttractions.length?'先核對最多 18 個日期候選行程，優先推薦行程概要提及較多指定景點者，再依出發日排序；景點名稱採文字比對，未找到不代表未安排，車經、入內及替代安排仍需確認。':'公開官網即時讀取；先核對最多 18 個日期候選行程，依出發日排序，選不同路線最多三筆。適合度仍需業務確認。'};}
